import type { ThemeRegistrationRaw } from "shiki/core"

export const gruvcraftDark = {
  name: "gruvcraft-dark",
  type: "dark" as const,
  bg: "#2a2928",
  fg: "#d4be98",
  colors: {
    "editor.background": "#2a2928",
    "editor.foreground": "#d4be98",
    "editorLineNumber.foreground": "#695e55",
    "editorCursor.foreground": "#e6d5ae",
    "editor.selectionBackground": "#3b3634",
    "editor.lineHighlightBackground": "#33302e",
    "gitDecoration.addedResourceForeground": "#add400",
    "gitDecoration.deletedResourceForeground": "#545e2c",
    "gitDecoration.modifiedResourceForeground": "#b2ba8e",
  },
  settings: [
    { settings: { foreground: "#d4be98", background: "#2a2928" } },
    {
      scope: [
        "comment",
        "punctuation.definition.comment",
        "comment.block",
        "comment.line",
        "comment.block.documentation",
        "comment.line.documentation",
        "meta.documentation",
        "punctuation.definition.documentation",
      ],
      settings: { foreground: "#7c6f64" },
    },
    {
      scope: ["string", "punctuation.definition.string", "string.quoted", "string.template"],
      settings: { foreground: "#bac584" },
    },
    {
      scope: [
        "constant.numeric",
        "constant.numeric.integer",
        "constant.numeric.float",
        "constant.numeric.hex",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
        "constant.language.nan",
        "constant.language.infinity",
      ],
      settings: { foreground: "#de9880" },
    },
    {
      scope: [
        "constant.character.escape",
        "constant.other.escape",
        "string.regexp",
        "string.quoted.other.literal",
        "string.other.link",
        "string.other.path",
        "string.other.url",
        "punctuation.definition.string.begin",
        "punctuation.definition.string.end",
      ],
      settings: { foreground: "#d4be98" },
    },
    {
      scope: [
        "variable.other.constant",
        "support.constant",
        "constant.other",
        "entity.name.constant",
        "meta.definition.variable.constant",
        "meta.enum",
        "meta.enum constant.other",
      ],
      settings: { foreground: "#d6b37b" },
    },
    {
      scope: [
        "variable",
        "variable.other",
        "variable.parameter",
        "variable.language",
        "identifier",
        "meta.definition.variable",
        "keyword.operator.new",
        "keyword.other.new",
        "support.function.constructor",
        "meta.instance.constructor",
      ],
      settings: { foreground: "#d6b37b" },
    },
    {
      scope: ["variable.other.property", "variable.other.member", "support.variable.property", "support.variable"],
      settings: { foreground: "#d4be98" },
    },
    {
      scope: [
        "keyword",
        "keyword.control",
        "keyword.control.conditional",
        "keyword.control.loop",
        "keyword.operator",
        "keyword.other",
        "storage.modifier",
        "storage",
        "storage.type",
      ],
      settings: { foreground: "#d4be98" },
    },
    {
      scope: [
        "keyword.control.import",
        "keyword.control.export",
        "keyword.control.from",
        "keyword.control.using",
        "keyword.control.directive",
        "keyword.control.flow",
        "storage.modifier.async",
        "meta.preprocessor",
        "keyword.other.directive",
        "punctuation.definition.directive",
      ],
      settings: { foreground: "#d4a599" },
    },
    {
      scope: [
        "entity.name.function",
        "entity.name.function.member",
        "entity.name.function.method",
        "support.function",
        "support.function.any-method",
        "support.function.builtin",
        "variable.function",
        "meta.function-call entity.name.function",
        "meta.function-call variable.function",
        "meta.method-call entity.name.function",
        "meta.method-call variable.function",
        "meta.function-call support.function",
        "meta.method-call support.function",
      ],
      settings: { foreground: "#b2ba8e" },
    },
    {
      scope: [
        "meta.function entity.name.function",
        "meta.function.declaration entity.name.function",
        "meta.function.definition entity.name.function",
        "meta.function.expression entity.name.function",
        "meta.method entity.name.function",
        "meta.definition.method entity.name.function",
        "meta.class meta.method entity.name.function",
        "meta.class meta.definition.method entity.name.function",
      ],
      settings: { foreground: "#adb79d", fontStyle: "bold" },
    },
    {
      scope: [
        "meta.decorator",
        "meta.annotation",
        "punctuation.definition.decorator",
        "entity.name.function.decorator",
      ],
      settings: { foreground: "#adb79d", fontStyle: "bold" },
    },
    {
      scope: [
        "entity.name.type",
        "support.type",
        "support.class",
        "entity.name.class",
        "entity.name.struct",
        "entity.name.interface",
        "entity.name.enum",
        "meta.type",
      ],
      settings: { foreground: "#e6d5ae" },
    },
    {
      scope: [
        "support",
        "support.other",
        "meta.interpolation",
        "punctuation.section.interpolation",
        "punctuation.definition.interpolation",
        "punctuation.special",
      ],
      settings: { foreground: "#b2ba8e" },
    },
    {
      scope: [
        "punctuation.separator",
        "punctuation.terminator",
        "punctuation.definition.parameters",
        "punctuation.definition.arguments",
        "punctuation.definition.array",
        "punctuation.definition.object",
        "punctuation.definition.block",
        "punctuation.definition.tag",
        "punctuation.definition.template-expression",
        "meta.brace",
      ],
      settings: { foreground: "#ca9a70" },
    },
    {
      scope: [
        "punctuation.section.group.begin",
        "punctuation.section.group.end",
        "punctuation.section.brackets.begin",
        "punctuation.section.brackets.end",
        "punctuation.section.block.begin",
        "punctuation.section.block.end",
      ],
      settings: { foreground: "#d6b37b" },
    },
    { scope: ["heading.1.markdown"], settings: { foreground: "#d4a599", fontStyle: "bold" } },
    { scope: ["heading.2.markdown"], settings: { foreground: "#eead83", fontStyle: "bold" } },
    { scope: ["heading.3.markdown"], settings: { foreground: "#de9880", fontStyle: "bold" } },
    {
      scope: ["heading.4.markdown", "heading.5.markdown", "heading.6.markdown"],
      settings: { foreground: "#d6b37b", fontStyle: "bold" },
    },
    {
      scope: ["markup.bold.markdown", "punctuation.definition.bold.markdown"],
      settings: { fontStyle: "bold" },
    },
    {
      scope: ["markup.italic.markdown", "punctuation.definition.italic.markdown"],
      settings: { fontStyle: "italic" },
    },
    {
      scope: ["markup.strikethrough.markdown", "punctuation.definition.strikethrough.markdown"],
      settings: { fontStyle: "strikethrough" },
    },
    {
      scope: ["markup.inline.raw.string.markdown", "punctuation.definition.raw.markdown"],
      settings: { foreground: "#bac584", background: "#3b3634" },
    },
    { scope: ["markup.fenced_code.block.markdown"], settings: { background: "#3b3634" } },
    {
      scope: ["punctuation.definition.markdown", "fenced_code.block.language.markdown"],
      settings: { foreground: "#d4be98", background: "#3b3634" },
    },
    { scope: ["punctuation.definition.list.begin.markdown"], settings: { foreground: "#ca9a70" } },
    { scope: ["punctuation.definition.quote.begin.markdown"], settings: { foreground: "#4c4641" } },
    {
      scope: ["markup.quote.markdown", "markup.table.markdown"],
      settings: { foreground: "#695e55" },
    },
    { scope: ["punctuation.separator.table.markdown"], settings: { foreground: "#4c4641" } },
    {
      scope: ["string.other.link.title.markdown", "markup.underline.link.markdown"],
      settings: { foreground: "#adb79d" },
    },
    { scope: ["entity.name.tag"], settings: { foreground: "#d4be98" } },
    { scope: ["support.class.component"], settings: { foreground: "#ca9a70" } },
    {
      scope: ["entity.other.attribute-name", "meta.attribute"],
      settings: { foreground: "#d4be98" },
    },
    {
      scope: ["markup.inserted", "meta.diff.header.to-file"],
      settings: { foreground: "NONE", background: "#51592a" },
    },
    {
      scope: ["markup.deleted", "meta.diff.header.from-file"],
      settings: { foreground: "#695e55", background: "#373a20" },
    },
    { scope: ["markup.changed"], settings: { foreground: "#695e55", background: "#414526" } },
    {
      scope: ["invalid", "invalid.illegal"],
      settings: { foreground: "#2a2928", background: "#ea6962" },
    },
  ],
} satisfies ThemeRegistrationRaw

export const gruvcraftLight = {
  name: "gruvcraft-light",
  type: "light" as const,
  bg: "#fbf1c7",
  fg: "#3c3836",
  colors: {
    "editor.background": "#fbf1c7",
    "editor.foreground": "#3c3836",
    "editorLineNumber.foreground": "#7c6f64",
    "editorCursor.foreground": "#282828",
    "editor.selectionBackground": "#ebdbb2",
    "editor.lineHighlightBackground": "#f2e5bc",
    "gitDecoration.addedResourceForeground": "#add400",
    "gitDecoration.deletedResourceForeground": "#545e2c",
    "gitDecoration.modifiedResourceForeground": "#b2ba8e",
  },
  settings: [
    { settings: { foreground: "#3c3836", background: "#fbf1c7" } },
    {
      scope: [
        "comment",
        "punctuation.definition.comment",
        "comment.block",
        "comment.line",
        "comment.block.documentation",
        "comment.line.documentation",
        "meta.documentation",
        "punctuation.definition.documentation",
      ],
      settings: { foreground: "#928374" },
    },
    {
      scope: ["string", "punctuation.definition.string", "string.quoted", "string.template"],
      settings: { foreground: "#79740e" },
    },
    {
      scope: [
        "constant.numeric",
        "constant.numeric.integer",
        "constant.numeric.float",
        "constant.numeric.hex",
        "constant.language.boolean",
        "constant.language.null",
        "constant.language.undefined",
        "constant.language.nan",
        "constant.language.infinity",
      ],
      settings: { foreground: "#af3a03" },
    },
    {
      scope: [
        "constant.character.escape",
        "constant.other.escape",
        "string.regexp",
        "string.quoted.other.literal",
        "string.other.link",
        "string.other.path",
        "string.other.url",
        "punctuation.definition.string.begin",
        "punctuation.definition.string.end",
      ],
      settings: { foreground: "#3c3836" },
    },
    {
      scope: [
        "variable.other.constant",
        "support.constant",
        "constant.other",
        "entity.name.constant",
        "meta.definition.variable.constant",
        "meta.enum",
        "meta.enum constant.other",
        "variable",
        "variable.other",
        "variable.parameter",
        "variable.language",
        "identifier",
        "meta.definition.variable",
        "keyword.operator.new",
        "keyword.other.new",
        "support.function.constructor",
        "meta.instance.constructor",
      ],
      settings: { foreground: "#b57614" },
    },
    {
      scope: ["variable.other.property", "variable.other.member", "support.variable.property", "support.variable"],
      settings: { foreground: "#3c3836" },
    },
    {
      scope: [
        "keyword",
        "keyword.control",
        "keyword.control.conditional",
        "keyword.control.loop",
        "keyword.operator",
        "keyword.other",
        "storage.modifier",
        "storage",
        "storage.type",
      ],
      settings: { foreground: "#9d0006" },
    },
    {
      scope: [
        "keyword.control.import",
        "keyword.control.export",
        "keyword.control.from",
        "keyword.control.using",
        "keyword.control.directive",
        "keyword.control.flow",
        "storage.modifier.async",
        "meta.preprocessor",
        "keyword.other.directive",
        "punctuation.definition.directive",
      ],
      settings: { foreground: "#8f3f71" },
    },
    {
      scope: [
        "entity.name.function",
        "entity.name.function.member",
        "entity.name.function.method",
        "support.function",
        "support.function.any-method",
        "support.function.builtin",
        "variable.function",
        "meta.function-call entity.name.function",
        "meta.function-call variable.function",
        "meta.method-call entity.name.function",
        "meta.method-call variable.function",
        "meta.function-call support.function",
        "meta.method-call support.function",
      ],
      settings: { foreground: "#076678" },
    },
    {
      scope: [
        "meta.function entity.name.function",
        "meta.function.declaration entity.name.function",
        "meta.function.definition entity.name.function",
        "meta.function.expression entity.name.function",
        "meta.method entity.name.function",
        "meta.definition.method entity.name.function",
        "meta.class meta.method entity.name.function",
        "meta.class meta.definition.method entity.name.function",
      ],
      settings: { foreground: "#076678", fontStyle: "bold" },
    },
    {
      scope: [
        "meta.decorator",
        "meta.annotation",
        "punctuation.definition.decorator",
        "entity.name.function.decorator",
      ],
      settings: { foreground: "#076678", fontStyle: "bold" },
    },
    {
      scope: [
        "entity.name.type",
        "support.type",
        "support.class",
        "entity.name.class",
        "entity.name.struct",
        "entity.name.interface",
        "entity.name.enum",
        "meta.type",
        "support",
        "support.other",
        "meta.interpolation",
        "punctuation.section.interpolation",
        "punctuation.definition.interpolation",
        "punctuation.special",
      ],
      settings: { foreground: "#427b58" },
    },
    {
      scope: [
        "punctuation.separator",
        "punctuation.terminator",
        "punctuation.definition.parameters",
        "punctuation.definition.arguments",
        "punctuation.definition.array",
        "punctuation.definition.object",
        "punctuation.definition.block",
        "punctuation.definition.tag",
        "punctuation.definition.template-expression",
        "meta.brace",
      ],
      settings: { foreground: "#7c6f64" },
    },
    {
      scope: [
        "punctuation.section.group.begin",
        "punctuation.section.group.end",
        "punctuation.section.brackets.begin",
        "punctuation.section.brackets.end",
        "punctuation.section.block.begin",
        "punctuation.section.block.end",
      ],
      settings: { foreground: "#b57614" },
    },
    { scope: ["heading.1.markdown"], settings: { foreground: "#9d0006", fontStyle: "bold" } },
    { scope: ["heading.2.markdown"], settings: { foreground: "#af3a03", fontStyle: "bold" } },
    { scope: ["heading.3.markdown"], settings: { foreground: "#b57614", fontStyle: "bold" } },
    {
      scope: ["heading.4.markdown", "heading.5.markdown", "heading.6.markdown"],
      settings: { foreground: "#076678", fontStyle: "bold" },
    },
    {
      scope: ["markup.bold.markdown", "punctuation.definition.bold.markdown"],
      settings: { fontStyle: "bold" },
    },
    {
      scope: ["markup.italic.markdown", "punctuation.definition.italic.markdown"],
      settings: { fontStyle: "italic" },
    },
    {
      scope: ["markup.strikethrough.markdown", "punctuation.definition.strikethrough.markdown"],
      settings: { fontStyle: "strikethrough" },
    },
    {
      scope: ["markup.inline.raw.string.markdown", "punctuation.definition.raw.markdown"],
      settings: { foreground: "#79740e", background: "#ebdbb2" },
    },
    { scope: ["markup.fenced_code.block.markdown"], settings: { background: "#ebdbb2" } },
    {
      scope: ["punctuation.definition.markdown", "fenced_code.block.language.markdown"],
      settings: { foreground: "#3c3836", background: "#ebdbb2" },
    },
    {
      scope: ["punctuation.definition.list.begin.markdown", "markup.quote.markdown", "markup.table.markdown"],
      settings: { foreground: "#7c6f64" },
    },
    {
      scope: ["punctuation.definition.quote.begin.markdown", "punctuation.separator.table.markdown"],
      settings: { foreground: "#d5c4a1" },
    },
    {
      scope: ["string.other.link.title.markdown", "markup.underline.link.markdown"],
      settings: { foreground: "#076678" },
    },
    { scope: ["entity.name.tag"], settings: { foreground: "#9d0006" } },
    { scope: ["support.class.component"], settings: { foreground: "#b57614" } },
    {
      scope: ["entity.other.attribute-name", "meta.attribute"],
      settings: { foreground: "#427b58" },
    },
    {
      scope: ["markup.inserted", "meta.diff.header.to-file"],
      settings: { foreground: "NONE", background: "#d5f5d0" },
    },
    {
      scope: ["markup.deleted", "meta.diff.header.from-file"],
      settings: { foreground: "#7c6f64", background: "#f7d0d0" },
    },
    { scope: ["markup.changed"], settings: { foreground: "#7c6f64", background: "#f5e6b3" } },
    {
      scope: ["invalid", "invalid.illegal"],
      settings: { foreground: "#fbf1c7", background: "#cc241d" },
    },
  ],
} satisfies ThemeRegistrationRaw
